services:
  base:
    image: tmp_del
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /workspaces/nvblox
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../../../:/workspaces/nvblox
    privileged: true
    network_mode: host
    runtime: nvidia
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-ic","tail -f /dev/null"]