/**:
  ros__parameters:
    # Lidar settings
    use_lidar: false
    # QoS settings
    input_qos: "SENSOR_DATA"
    # Map clearing settings
    map_clearing_frame_id: "pelvis"
    map_clearing_radius_m: 0.0
    # Rviz visualization
    esdf_slice_bounds_visualization_attachment_frame_id: "d435_link"
    decay_tsdf_rate_hz: 0.0

    static_mapper:
      esdf_slice_height: -1.0
      # Expected to be tuned by users. Slice height depends on realsense mounting.
      esdf_slice_min_height: -1.1
      esdf_slice_max_height: -0.9

    dynamic_mapper:
      esdf_slice_height: -1.0
      # Expected to be tuned by users. Slice height depends on realsense mounting.
      esdf_slice_min_height: -1.1
      esdf_slice_max_height: -0.9